pipeline:
  name: Build curator
  identifier: Build_curator_1688168496215
  projectIdentifier: Apache_Curator
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesHosted
            spec:
              identifier: k8s-hosted-infra
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: ./gradlew clean build
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: simona-bateman/curator
        build: <+input>
